### ISSUE TITLE
Instruction books useless

### ISSUE THREAD

**Issue by 4rz0** [oitsjustjose/V-Tweaks#12]
The Instruction Books given when starting a new map are useless since they're missing any content.
![image1](https://dl.dropboxusercontent.com/s/2kvs93rc0us1lln/javaw_2016-06-01_21-12-18.png?dl=0)
![image2](https://dl.dropboxusercontent.com/s/bkdy49024nbiz7l/javaw_2016-06-01_21-15-08.png?dl=0)

**Comment by oitsjustjose** [comment]
I've fixed this in every other version except for 1.9, since 1.9 is kind of an unwanted step-child in MC modding. But here's an [unofficial build](http://puu.sh/pd4xu/e11504f6ce.jar) of V-Tweaks on 1.9 that has more features and gets rid of these guidebooks and implements the changes put in 1.9.4 / 1.8.9 versions.

**Comment by 4rz0** [comment]
Ah, good to hear.
Yep, sounds reasonable.
Thanks for the fast response!
