### ISSUE TITLE
support for The One Probe

### ISSUE THREAD

**Issue by Hypsellis** [oitsjustjose/V-Tweaks#15]
The challenger mobs prefixes don't display in The One Probe menu and displays at the top center like if Waila was installed.

**Comment by oitsjustjose** [comment]
This sounds more like a feature for @McJty to add to TOP, rather than myself, because all I'm doing is renaming the Challenger Mobs the same method that name tags rename entities. You should probably ask McJty for TOP to show the custom name of an entity if it has one, rather than always going for its localized name :)
