### ISSUE TITLE
dropped items from challenger mobs are broken

### ISSUE THREAD

**Issue by MCJediYoda** [oitsjustjose/V-Tweaks#27]
I did some testing and version 1.4.10.0 and 1.4.10.1 doesn't drop the correct item from challenger mobs.  I went back to version 1.4.9.16 and the items do drop properly.  Currently the items will drop with missing item textures and I cant seem to craft anything with them.  It does seem to have the correct item name.

I am using Forge 1.10.2 - 12.18.3.2281.  And this is just using a test world with V-Tweaks, Neat and JEI

Thanks for checking into this.

**Comment by oitsjustjose** [comment]
So this is partially my fault; I rewrote my config parser to be more generalized, but in the process I changed the functionality and forgot to update the config file to reflect this. The new layout is such:

If you want to add an Item/Block with Metadata and Quantity, do:

`<modid>:<item>:<meta>*<quantity>`, example: `minecraft:dye:8*1` adds **One** Gray Dye

If you want to add an Item/Block **with** Meta but **without** Quantity, do:

`<modid>:<item>:<metadata>`, example: `minecraft:dye:15` adds a drop entry consisting of 1 bonemeal

If you want to add an Item/Block **without** Meta or Quantity, do:

`<modid>:<item>`, example: `minecraft:saddle` drops a saddle. That's it. Just a saddle, no special data.

**If you want to add an item with quantity but without metadata, you have to include '0' as the Metadata**. This is just because it makes my regex parsing much easier and much more efficient, so maybe that was your problem? I haven't implemented an option for `<modid>:<item>*<quantity> in this config I'm afraid. I went and tested this thoroughly and using _this_ layout, it worked for me using other mods.

Hope this helps, next release will have an updated config file clarifying the configs _correctly_ :)

**Comment by MCJediYoda** [comment]
Awesome thank you.
