### ISSUE TITLE
2 diffent crash reports when testing

### ISSUE THREAD

**Issue by EternalOne11** [oitsjustjose/V-Tweaks#50]
https://paste.dimdev.org/edekaqimug.mccrash just a few fish according to vanilla tweaks
https://paste.dimdev.org/ijasokemon.mccrash hammer core according to vanilla tweaks

**Comment by oitsjustjose** [comment]
No, line 9 in both are the same: `at com.oitsjustjose.vtweaks.event.mobtweaks.ChallengerMobs.registerEvent(ChallengerMobs.java:40)
`
I was looking and it seems that you have set Challenger Mobs `Rarity` to 0 instead of just disabling them? I can make a catch for this but a good "right now" solution is to turn `Enable Tweak` to `false` and setting `Rarity` to anything larger than 0.

**Comment by EternalOne11** [comment]
thanks
