### ISSUE TITLE
Exponential growth

### ISSUE THREAD

**Issue by ZeekDaGeek** [oitsjustjose/V-Tweaks#69]
Egg Hatching doesn't seem to consider exponential growth at all, if you have chunk loaders you're going to crash a server with the option enabled, it doesn't matter how low the chance is if it doesn't check how many chickens are around it when hatching it will grow out of control.

![dJslK](https://user-images.githubusercontent.com/1709288/78454420-27305c80-7655-11ea-9b40-d871f526c602.png)
![EYA6V](https://user-images.githubusercontent.com/1709288/78454424-2bf51080-7655-11ea-9dbd-7b93b6d6a693.png)

I had to disable the feature.

**Comment by oitsjustjose** [comment]
Yep, I'm aware, that's why there's a choice to disable the feature and change the chance for egg hatching. If you have any ideas for how to consider exponential growth then I'd be glad to hear it! I could always scan a huge radius to see if there are any chickens nearby, but that sounds computationally expensive for such  a simple feature.

**Comment by yezhiyi9670** [comment]
This should happen because chickens don't die naturally. Maybe vanilla mob capabilities should be used to limit chickens.

**Comment by oitsjustjose** [comment]
I think that for now I'm going to close this and just leave it there. It's been in the game for a long time and I'll probably remove the feature soon enough, but I *could* kill the hatcher of said egg on a random chance. Just a thought.
