### ISSUE TITLE
Crash while Capabilities Being Attached

### ISSUE THREAD

**Issue by Syrikal** [oitsjustjose/V-Tweaks#80]
I had a crash tonight after some heavy lag, and when I checked the log it was full of messages saying '[01Feb2021 23:03:57.431] [Server thread/INFO] [com.oitsjustjose.vtweaks.VTweaks/]: V-Tweaks capability attached for minecraft:overworld' at various times. I'm not 100% sure this is the culprit, but it seems pretty likely.

latest.log:
[latest.log](https://github.com/oitsjustjose/V-Tweaks/files/5908965/latest.log)

**Comment by oitsjustjose** [comment]
Your issue is almost certainly elsewhere. The `V-Tweaks capability has attached for <modid:dimension>` uses the Forge event handler for when a server world is loaded. This means that your issue is deeply ingrained with some other mod causing your world to unload/reload more than just once, which would explain your lag. 

Also this capability is literally just used to store which players have been told about the online wiki lol, it shouldn't be causing anything this severe.

**Comment by Syrikal** [comment]
Hmmm. Noted. I'll poke around at my other mods. Thanks for the help!
