### ISSUE TITLE
blazes break the champion function by spawning an exesive amount of flint and steel.

### ISSUE THREAD

**Issue by EternalOne11** [oitsjustjose/V-Tweaks#89]
![2021-05-20_18 17 07](https://user-images.githubusercontent.com/42950385/119057734-06cb7a80-b99b-11eb-9b50-a6ce86370e67.png)

**Comment by oitsjustjose** [comment]
I uh.....


What? 

What other mods do you have installed?

**Comment by EternalOne11** [comment]
let me do some testing quickly. (alot of other mods.) (but very few effect the blaze. (think it might be back tools but that is all I can think of.)

**Comment by Reshirou** [comment]
This is very easy to test; just remove everything except V Tweaks and whatever mod you're using that shows that in world GUI (maybe it's ToB?) and then add back mods in bulk of 10 or 20 at a time until the bug is found again

Turn challenger spawn chance up to 100 in V Tweaks config for your testing

**Comment by oitsjustjose** [comment]
Closing as bug is stale - reopen if needed :)
